spring:
  application:
    name: spring-ws-client

server:
  port: 8081

ws:
 server:
   uri: http://localhost:8080/ws

logging:
  level:
    io.github.ehayik.kata.ws.client.LoggingInterceptor: DEBUG
